# Generated by Django 6.1.1 on 2026-09-18 15:33

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
        ('inventory', '0002_category_is_active'),
        ('sales', '0002_creditnote_creditnoteline_periodicinvoice_salesquote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='client_type',
            field=models.CharField(choices=[('individual', 'Individual / فردي'), ('commercial', 'Commercial / تجاري')], default='commercial', max_length=15),
        ),
        migrations.AddField(
            model_name='customer',
            name='commercial_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='commercial_reg',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipping_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipping_postal_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipping_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipping_street1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipping_street2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='street1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='street2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='adjustment_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='adjustment_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='global_discount_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount / مبلغ ثابت'), ('percent', 'Percentage / نسبة مئوية')], default='fixed', max_length=10),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='global_discount_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='has_shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='is_paid_upfront',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='issue_date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='payment_terms_days',
            field=models.PositiveIntegerField(default=0, help_text='Payment terms in days'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='shipping_address_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='shipping_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='shipping_recipient',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='template_design',
            field=models.CharField(blank=True, default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='terms_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='upfront_payment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='upfront_payment_method',
            field=models.CharField(blank=True, default='cash', max_length=30),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='upfront_payment_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percentage (%)'), ('fixed', 'Fixed Amount')], default='percent', max_length=10),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='tax2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines_tax2', to='accounting.taxrate'),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines_tax1', to='accounting.taxrate'),
        ),
    ]
