# Generated by Django 6.1.1 on 2026-09-18 15:34

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
        ('inventory', '0002_category_is_active'),
        ('sales', '0003_customer_city_customer_client_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesquote',
            name='adjustment_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='salesquote',
            name='adjustment_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='salesquote',
            name='global_discount_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount / مبلغ ثابت'), ('percent', 'Percentage / نسبة مئوية')], default='fixed', max_length=10),
        ),
        migrations.AddField(
            model_name='salesquote',
            name='global_discount_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='salesquote',
            name='has_shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesquote',
            name='payment_terms_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesquote',
            name='shipping_address_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salesquote',
            name='shipping_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='salesquote',
            name='shipping_recipient',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='salesquote',
            name='terms_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salesquote',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='salesquoteline',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='salesquoteline',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percentage (%)'), ('fixed', 'Fixed Amount')], default='percent', max_length=10),
        ),
        migrations.AddField(
            model_name='salesquoteline',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quote_lines_tax1', to='accounting.taxrate'),
        ),
        migrations.AddField(
            model_name='salesquoteline',
            name='tax2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quote_lines_tax2', to='accounting.taxrate'),
        ),
        migrations.AddField(
            model_name='salesquoteline',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_lines', to='inventory.warehouse'),
        ),
    ]
