# Generated by Django 6.1.1 on 2026-09-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salesquote_adjustment_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salessettings',
            name='default_terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='next_invoice_number',
            field=models.PositiveIntegerField(default=1, help_text='رقم الفاتورة التالي'),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='number_padding',
            field=models.PositiveSmallIntegerField(default=4, help_text='عدد خانات الرقم (مثال: 4 خانات تعطي 0001)'),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='numbering_format',
            field=models.CharField(choices=[('prefix_num', 'بادئة ورقم متسلسل (مثال: INV-0001)'), ('prefix_year_num', 'بادئة وسنة ورقم (مثال: INV-2026-0001)'), ('prefix_month_num', 'بادئة وشهر وسنة ورقم (مثال: INV-2026-09-0001)')], default='prefix_num', max_length=30),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='receipt_prefix',
            field=models.CharField(default='RCPT', max_length=10),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='reset_sequence_yearly',
            field=models.BooleanField(default=False, help_text='إعادة تصفير الترقيم سنوياً'),
        ),
    ]
