# Generated by Django 6.1.1 on 2026-09-18 16:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salessettings_default_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Exchange rate to base currency', max_digits=14),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Exchange rate to base currency', max_digits=14),
        ),
        migrations.AddField(
            model_name='salesquote',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Exchange rate to base currency', max_digits=14),
        ),
    ]
