# Generated by Django 6.1.1 on 2026-09-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('accountant', 'Accountant'), ('sales', 'Sales'), ('purchasing', 'Purchasing'), ('warehouse', 'Warehouse'), ('manufacturing', 'Manufacturing'), ('hr', 'Human Resources'), ('viewer', 'Viewer')], max_length=20, unique=True),
        ),
    ]
