# Generated by Django 6.1.1 on 2026-09-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='base_currency',
            field=models.CharField(default='EGP', max_length=3),
        ),
    ]
