# Generated by Django 6.1.1 on 2026-09-18 15:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
        ('inventory', '0002_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, help_text='الماركة / العلامة التجارية', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='min_sale_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='أقل سعر بيع', max_digits=14),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_tax1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_ptax1', to='accounting.taxrate'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_tax2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_ptax2', to='accounting.taxrate'),
        ),
        migrations.AddField(
            model_name='product',
            name='tax1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_tax1', to='accounting.taxrate'),
        ),
        migrations.AddField(
            model_name='product',
            name='tax2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_tax2', to='accounting.taxrate'),
        ),
    ]
